list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/buttons/button_normal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/buttons/button_warning_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/list/list_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/round_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/section_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/sliderbox_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/widget_items/segment_item/segment_item_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_14_c_array_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_16_bin_file_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Montserrat_Medium_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flower_data_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/animations/screen_animations_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/assets/screen_assets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/data_bindings/screen_data_bindings_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/hello_world/screen_hello_world_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layout/screen_layouts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/new_component/screen_components_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/new_widget/screen_widgets/screen_widgets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screens/screen_about_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screens/screen_main_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/screen_styles_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/translations/screen_translations_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/tutorials_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/tutorials.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/wd_segment/wd_segment.c)