#!/bin/bash
# Print a C example list for the emscripten docs build.
# Usage: genexamplelist.sh <examples-dir>   (e.g. examples/lvgl_pro)
EXAMPLES_DIR="${1:?usage: genexamplelist.sh <examples-dir>}"
echo "/* Autogenerated */"
echo '#include <stddef.h>'
echo '#include "examplelist.h"'
TMPFILE=$(mktemp)
find "$EXAMPLES_DIR" -name \*.c | xargs grep -hE "^void lv_(example)" | sed 's/(/ /g' | awk '{print $2}' > $TMPFILE
cat $TMPFILE | while read -r line; do
echo "extern void ${line}(void);"
done
echo "const struct lv_ci_example lv_ci_example_list[] = {"
cat $TMPFILE | while read -r line; do
echo "    { \"$line\", $line },";
done
echo "    { NULL, NULL }"
echo "};"
