list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_example_large_large_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_arc_bg_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_arc_indicator_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_bar_bg_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_bar_indicator_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/img_example_lvgl_logo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_open_examples_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/lvgl_open_examples.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_align_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_flow_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_grow_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_ignore_layout_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_internal_padding_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_new_track_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/flex/lv_example_flex_rtl_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_align_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_cell_span_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_descriptors_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_fr_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_ignore_layout_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_internal_padding_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_rtl_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/layouts/grid/lv_example_grid_subgrid_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/libs/qrcode/qrcode_basic/lv_example_qrcode_basic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_chain_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_floating_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_one_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_overview_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_rtl_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_scrollable_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_scrollbar_mode_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_scrollbar_style_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/scroll/lv_example_scroll_snap_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_background_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_blur_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_border_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_image_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_local_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_margin_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_multiple_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_opacity_transform_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_outline_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_padding_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_parts_states_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_shadow_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_size_position_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/styles/lv_example_style_text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_change_rate_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_img_indicator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_mode_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_pie_chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_rotation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_set_angles_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/arc/lv_example_arc_value_range_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_img_indicator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_modes_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_orientation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/bar/lv_example_bar_value_range_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/button/lv_example_button_basic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/button/lv_example_button_states_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/button/lv_example_button_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_button_ctrl_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_button_width_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_map_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_one_checked_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_popover_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_recolor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/buttonmatrix/lv_example_buttonmatrix_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/calendar/lv_example_calendar_basic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/chart/lv_example_chart_cursor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/chart/lv_example_chart_scrollable_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/chart/lv_example_chart_series_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/chart/lv_example_chart_ticks_labels_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/chart/lv_example_chart_types_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/checkbox/lv_example_checkbox_bind_checked_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/checkbox/lv_example_checkbox_states_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/checkbox/lv_example_checkbox_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/checkbox/lv_example_checkbox_text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/dropdown/lv_example_dropdown_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/dropdown/lv_example_dropdown_direction_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/dropdown/lv_example_dropdown_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/dropdown/lv_example_dropdown_text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/image/lv_example_image_inner_align_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/image/lv_example_image_recolor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/image/lv_example_image_src_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/image/lv_example_image_transformations_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/keyboard/lv_example_keyboard_modes_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/keyboard/lv_example_keyboard_popovers_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/keyboard/lv_example_keyboard_textarea_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_bind_text_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_long_mode_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_recolor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_set_text_newline_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/label/lv_example_label_text_align_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/led/lv_example_led_brightness_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/led/lv_example_led_color_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/led/lv_example_led_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/obj/lv_example_obj_bind_style_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/roller/lv_example_roller_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/roller/lv_example_roller_options_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/roller/lv_example_roller_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/roller/lv_example_roller_visible_rows_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/scale/lv_example_scale_bind_section_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/scale/lv_example_scale_modes_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/scale/lv_example_scale_range_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/scale/lv_example_scale_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/scale/lv_example_scale_ticks_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_bind_state_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_img_indicator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_modes_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_reversed_direction_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/slider/lv_example_slider_value_range_orientation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/span/lv_example_span_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinbox/lv_example_spinbox_bind_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinbox/lv_example_spinbox_format_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinbox/lv_example_spinbox_rollover_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinbox/lv_example_spinbox_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinbox/lv_example_spinbox_value_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/spinner/lv_example_spinner_basic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/switch/lv_example_switch_orientation_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/switch/lv_example_switch_state_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/switch/lv_example_switch_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_cells_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_merge_cells_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_rows_columns_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_scroll_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_styling_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/table/lv_example_table_width_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/tabview/lv_example_tabview_active_tab_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/tabview/lv_example_tabview_basic_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/tabview/lv_example_tabview_tab_bar_position_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/tabview/lv_example_tabview_tab_bar_style_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/tabview/lv_example_tabview_tab_button_content_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/textarea/lv_example_textarea_cursor_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/widgets/textarea/lv_example_textarea_placeholder_gen.c)